### ISSUE TITLE
Make it active ;) and fix some issues

### ISSUE THREAD

**Issue by hahahahacker2009** [ringwormGO-organization/Termi-Lua#3]
I have reviewed the Termi-Lua code and I see some cons of the function.

The way to run commands is passive, means you have registered commands in main.lua file can be run. Why don't check for function/{input}.lua file instead of it?

Also Termi-Lua has some problem with the command line because some code is not properly run. This is the screenshot
![image](https://user-images.githubusercontent.com/86903124/157431001-0d555ad3-7600-463e-b451-6d235106f49d.png)
 I entered invalid commands and it doesn't say anything

**Comment by Andrej123456789** [comment]
I tried to implement but I will fixed soon

**Comment by Andrej123456789** [comment]
Fixed with [this commit](https://github.com/ringwormGO-organization/Termi-Lua/commit/e7d67d4bc16436619ae71cf51b313f2e923b1aac).
Issue will be closed.

**Comment by hahahahacker2009** [comment]
This issue is just partially fixed, it still run passively. Can you reopen this?

**Comment by Andrej123456789** [comment]
Now is working, just part with `else`, for other contact @StjepanBM1

**Comment by Andrej123456789** [comment]
Second part of your issue is fixed with https://github.com/ringwormGO-organization/Termi-Lua/commit/9f8e5213a11f696901a177b28290a4ee05d8d431
